### ISSUE TITLE
Multiple Subreddits?

### ISSUE THREAD

**Issue by Readtt** [Milo123459/imageapi.js#1]
Is there a way to put multiple subreddits and not only one like: 

`let img = await imageapi("Kitsunemimi", "memes", "dankmemes' true);`

Also, if you want the image to actually be displayed, all you have to do is add, `message.channel.send(img);` on top of console.log(img);

**Comment by Milo123459** [comment]
Hey! You can not use imageapi.js in sequence like that, but I'll work on something to do that.

**Comment by Readtt** [comment]
Thanks!

**Comment by Milo123459** [comment]
No problem. As of right now I'm having a few issues. Update should be out soon.

**Comment by Readtt** [comment]
K, also, there's one other problem with nsfw subreddit's where when you put the subreddit "hentai" for example, it gives out an error: `(node:13764) UnhandledPromiseRejectionWarning: TypeError: Error, probably due to an invalid subreddit!`
