### ISSUE TITLE
Make more documentation on this.

### ISSUE THREAD

**Issue by Larkify** [Milo123459/imageapi.js#11]
This seems like a great package, the only exception is that there is little to no documentation on how to use it.

**Comment by Milo123459** [comment]
Hi, The readme has all required information. It's 3 functions, the default export, .stats and .advanced, all having intellisense in JavaScript and TypeScript. Check out the .d.ts if need be.

**Comment by Milo123459** [comment]
Hi @Larkify, if you need, you can check out the new readme. It comes with a few new features, including better docs.
