### ISSUE TITLE
Question: Is it possible to filter for non NSFW posts?

### ISSUE THREAD

**Issue by Larkify** [Milo123459/imageapi.js#12]

**Comment by Larkify** [comment]
If not, it would be really cool if you could!

**Comment by Larkify** [comment]
nvm, the original API doesn't have it.

**Comment by Milo123459** [comment]
Imageapi doesn't return nsfw images. No need for a filter

**Comment by Milo123459** [comment]
Fyi I made the api. If you have any suggestions let me know
