### ISSUE TITLE
It doesn't work.

### ISSUE THREAD

**Issue by soyscp** [Milo123459/imageapi.js#14]
Everytime I try to use it, it returns a FetchError.

If needed, I'll send the exact error message.

**Comment by Milo123459** [comment]
Please send the error message.

**Comment by Milo123459** [comment]
Right, can reproduce. I'm going to host it elsewhere and update the domains.

**Comment by soyscp** [comment]
Ok.

**Comment by Milo123459** [comment]
Nevermind, this project is more or less inactive. https://npmjs.com/package/subbey is a good alternative.

<blockquote><img src="https://static.npmjs.com/338e4905a2684ca96e08c7780fc68412.png" width="48" align="right"><div><img src="https://static.npmjs.com/da3ab40fb0861d15c83854c29f5f2962.png" height="14"> npm</div><div><strong><a href="https://www.npmjs.com/package/subbey">subbey</a></strong></div><div>subbey is an lightweight and asynchronous Reddit API wrapper to retrieve post easily</div></blockquote>
