### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by enffinity** [Milo123459/imageapi.js#6]
Is there any way i can possibly disable the `[IMAGEAPI.JS]: TOOK 706MS TO RECIEVE YOUR IMAGE. SUBREDDIT: dank IMAGE: http://imgur.com/73UYwcp.png REQUEST: 69921` message whenever is use this API?

**Comment by Milo123459** [comment]
Yes, add false as the second param, not true.

**Comment by Milo123459** [comment]
Let me know if it works.

**Comment by enffinity** [comment]
Works, thanks!
